source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'RatingCafe' do
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native'
  pod 'GoogleMaps'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
end
